/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo.taskhive;

import java.io.IOException;
import it.unibo.taskhive.services.SceneManager;
import it.unibo.taskhive.services.UserService;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Benvenuti nell'App TaskHive!";
    }

    @Override
    public void start(Stage stage) throws IOException {
        UserService userService = new UserService();
        userService.createSuperUserIfNotExists();
        
        SceneManager.setStage(stage);
        SceneManager.switchScene("fxml/LoginView.fxml");

    }

    public static void main(String[] args) {
        launch();
    }
}
