/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unibo.taskhive;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Benvenuti nell'App TaskHive!";
    }

    @Override
    public void start(Stage primaryStage) {
        Label welcomeLabel = new Label(getGreeting());

        // Layout Finestra
        VBox root = new VBox(welcomeLabel);
        root.setSpacing(10);
        root.setStyle("-fx-padding: 20; -fx-alignment: center;");

        // Scena Principale
        Scene scene = new Scene(root, 400, 200);

        // Configurazione della Finestra
        primaryStage.setTitle("TaskHive");
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }
}
